### ISSUE TITLE
OpenAI is assumed as default AI engine even if OPENAI_API_KEY not set and another one is set

### ISSUE THREAD

**Issue by TUMAAA** [ogre-run/miniogre#26]
Replicate:
- set GROQ_SECRET_ACCESS_KEY to any value you desire
- unset OPENAPI_API_KEY

Error:
OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

**Comment by TUMAAA** [comment]
It appears the GROQ key (and possibly the other ones other than that of OpenAI) are only mentioned in the main readme but never used in the code

**Comment by wilderlopes** [comment]
Fix proposed on miniogre v0.11.0-beta: https://pypi.org/project/miniogre/0.11.0b0/

In a nutshell, the default provider is now `ogre` instead of `openai`. Any user can get a **free** token at [app.ogre.run](https://app.ogre.run) and create a env variable `OGRE_API_KEY=<token>`

Release details: https://github.com/ogre-run/miniogre/releases/tag/v0.11.0-beta

@TUMAAA -- I would appreciate your feedback.

**Comment by TUMAAA** [comment]
> The current behavior (openai as default despite the inexistence of OPENAI_API_KEY) is expected. We want the user to have control over the pipeline and be sure about what LLM service/API will be run.

makes sense

**Comment by TUMAAA** [comment]
> Fix proposed on miniogre v0.11.0-beta: https://pypi.org/project/miniogre/0.11.0b0/
> 
> In a nutshell, the default provider is now `ogre` instead of `openai`. Any user can get a **free** token at [app.ogre.run](https://app.ogre.run) and create a env variable `OGRE_API_KEY=<token>`
> 
> Release details: https://github.com/ogre-run/miniogre/releases/tag/v0.11.0-beta
> 
> @TUMAAA -- I would appreciate your feedback.

Works like a charm. Makes sense to properly release

**Comment by wilderlopes** [comment]
Merged into main: https://github.com/ogre-run/miniogre/pull/30
