### ISSUE TITLE
The requirements inside the produced requirements.txt are not version pinned. Perhaps contradicts the idea of reproducibility

### ISSUE THREAD

**Issue by TUMAAA** [ogre-run/miniogre#29]
IMHO the versions should be either pinned to the constellation used during the running of miniogre run.
Alternatively, the version constellation corresponding with the commit date is taken

**Comment by wilderlopes** [comment]
Transition from simple requirements.txt to a [poetry](https://python-poetry.org/) pyproject.toml has been a long time coming (it has been in our roadmap since the April 2024).

Idea to implement this in the miniogre source code:
1. Generate the requirements.txt as usual
2. Create a function that creates a poetry env and does the following:
`$ cat requirements.txt | xargs poetry add`
or
`poetry add $(cat requirements.txt)`

**Comment by wilderlopes** [comment]
@TUMAAA 

Try this partial fix: https://pypi.org/project/miniogre/0.11.0b1/

**Comment by wilderlopes** [comment]
Closing this for now, as version v0.11.0 seems to solve the version lock. It might be revisited later on as we implement a way to do a Poetry-based version lock.
