### ISSUE TITLE
Analyze python notebook files `.ipynb` to extract requirements

### ISSUE THREAD

**Issue by wilderlopes** [ogre-run/miniogre#3]
## Problem

Several python projects, especially in data science, use .ipynb files. Currently, those files are not taken into account when retrieving the imported packages. This leads to inacuracies in the final list of requirements.

## Proposed solution

Convert .ipynb into .py and then use the existing method `extract_requirements_from_code` to retrieve the dependencies.

**Comment by Aftabby** [comment]
Hi @wilderlopes ,

I hope you're doing well. I noticed that this issue is currently assigned to you, and I'm interested in taking on the task myself. Since it seems like a straightforward issue, I believe I can handle it independently.

Would you mind if I take over this issue and work on it solo? I'm eager to contribute and confident in my ability to resolve it efficiently.
Please let me know if you're okay with reassigning the issue to me.

Thank you.

**Comment by Aftabby** [comment]
Hello @wilderlopes , Can you please review the code to check if everything is alright?
Thanks.

**Comment by wilderlopes** [comment]
Hi @Aftabby. After checking your pull request #8 (see comments there), I noticed there were some issues that needed fixing. In the process of fixing it, I realized it was better to take a totally new approach. 

Implemented in https://github.com/ogre-run/miniogre/commit/88067d9a4bd17a4ba51e99c0cff6d921cc2677a6
